version: '3.9'

services:
  web:
    build: 'C:/Users/Lenovo NZT/PycharmProjects/movie_app'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
    - db
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=config('DB_USER')
      - POSTGRES_PASSWORD=config('DB_PASSWORD')
      - POSTGRES_DB=DB_NAME
