# Generated by Django 4.0.4 on 2022-04-19 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('biography', 'Biography'), ('documentary', 'Documentary'), ('fantasy', 'Fantasy'), ('musical', 'Musical'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('drama', 'Drama'), ('crime', 'Crime'), ('horror', 'Horror'), ('family', 'Family'), ('animation', 'Animation')], max_length=20)),
                ('movie_title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('actors', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
